
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:file:./data/attendance-accounting

spring.datasource.username=password
spring.datasource.password=password
management.endpoints.web.exposure.include=health
management.endpoint.shutdown.enabled= true

server.error.include-message=always

attendance-accounting.security.jwt.secret=${ATTENDANCE_ACCOUNTING_JWT_SECRET}
spring.jpa.properties.hibernate.temp.use_jblc_metadata_defaults=false